### ISSUE TITLE
Feature Suggestion: Team Templates

### ISSUE THREAD

**Issue by JoshuaTheMiller** [cloudpups/github-teams-user-sync#28]
Feature suggestion, with no clear implementation yet: support for Team Templates.

**Comment by JoshuaTheMiller** [comment]
I'm intrigued by the concept of templates (think "matrices" for GitHub Action workflows) 🤔 It would still require some typing in the team sync file, but it would be much less and it would solve the whole "can't prevent teams from claiming names" issue.

```yml
GitHubTeamNames:
- template: 
   - GHEC_$TEAM_Admin   
   - GHEC_$TEAM_Writer
   - GHEC_$TEAM_Reader
  with:  	
   TEAM:
     - Team1
     - Team2
     - Team3
     - Team4
```
