### ISSUE TITLE
"Display Name" or similar 

### ISSUE THREAD

**Issue by nnordrum** [cloudpups/github-teams-user-sync#37]
```yaml
OrganizationMembersGroup: my_org_git_users
GitHubTeams:
  - name: Team A
    group: AZU_SOME_TEAM_USERS
  - name: CloudEnablement
    group: AZU_CE_ADMINS
```

Some way to make the name of the Team that is beings synced different than the group it's syncing to. This also facilitates more Team-scoped metadata later.

**Comment by nnordrum** [comment]
while you're at it, description is probably an easy add:

```
OrganizationMembersGroup: my_org_git_users
GitHubTeams:
  - name: Team A
    group: AZU_SOME_TEAM_USERS
    description: some description
  - name: CloudEnablement
    group: AZU_CE_ADMINS
    description: some description
```
