### ISSUE TITLE
Manage Copilot License teams

### ISSUE THREAD

**Issue by JoshuaTheMiller** [cloudpups/github-teams-user-sync#53]
A valuable feature for this bot to add is the ability to manage Copilot teams: https://docs.github.com/en/rest/copilot/copilot-business?apiVersion=2022-11-28#add-teams-to-the-copilot-business-subscription-for-an-organization

Note that this functionality should be marked as Beta and/or should include extra wrappers in case of failures- failure to set this due to API changes should not cause the whole bot to fail.

## Schema Options

I'm leaning towards Option 2 as it promotes the reuse of an existing team for granting Copilot Access while still granting the flexibility of having a designated team for Copilot access. With the top level property of Option 1, reuse for general repo access would not be possible.

The bot could support both concepts, though that may cause undue confusion 🤔 for now I am in favor of choosing one or the other.

### Option 1 - New top-level property

```yaml
OrganizationOwnersGroup: Some_Org_Owner_Group
OrganizationMembersGroup: Some_Group_To_Sync_For_Organization_Membership
GitHubTeamNames:
- Some_Team_To_Sync
AdditionalSecurityManagerGroups:
- Name: Some_SecurityManager_Team
- Name: Some_SecurityManager_Team_2
  DisplayName: Some Security Manager Team 2
# A new top level property
CopilotLicenseTeams:
- Name: Some_Copilot_Team
- Name: Some_Copilot_Team_2
  DisplayName: Some Copilot Team 2
Teams:
- Name: Some_Team
- Name: Some_Team_2
  DisplayName: Some Team 2
```

### Option 2 - New property on Teams

```yaml
OrganizationOwnersGroup: Some_Org_Owner_Group
OrganizationMembersGroup: Some_Group_To_Sync_For_Organization_Membership
GitHubTeamNames:
- Some_Team_To_Sync
AdditionalSecurityManagerGroups:
- Name: Some_SecurityManager_Team
- Name: Some_SecurityManager_Team_2
  DisplayName: Some Security Manager Team 2
Teams:
- Name: Some_Team
- Name: Some_Team_2
  DisplayName: Some Team 2
- Name: Some_Team_3
  DisplayName: Some Team 3
# A new property on individual Teams
  CopilotEnabled: true
```
