### ISSUE TITLE
Ability to add child teams

### ISSUE THREAD

**Issue by JoshuaTheMiller** [cloudpups/github-teams-user-sync#9]
As title says 🙂

It would be advantageous if this bot could support nesting Teams.

The team sync yaml could be enhanced to support something like the following:

```yml
# This property is used to control the addition of general Members to your Organization.
OrganizationMembersGroup: Some_Group_To_Sync_For_Organization_Membership
# This property is used for syncing all other GitHub Teams. Please note that users must also be a part of the `OrganizationMembersGroup` for the synchronization of the teams below to function properly.
GitHubTeamNames:
- Some_Team_To_Sync
- ParentTeam: Some_Other_Team_To_Sync
  ChildTeams:
  - Some_Child_Team_To_Sync
  - Some_Other_Child_Team_To_Sync
```
